-- Insert sample anime characters
INSERT INTO characters (name, anime, gender, age, hair_color, eye_color, occupation, personality, powers_abilities, backstory, notable_quotes, relationships, appearance_description, character_type) VALUES
(
    'Monkey D. Luffy',
    'One Piece',
    'Male',
    '19',
    'Black',
    'Black',
    'Pirate Captain',
    'Cheerful, determined, carefree, loyal to friends, loves adventure and meat. Simple-minded but has strong instincts. Never gives up on his dreams.',
    'Gomu Gomu no Mi (Rubber powers) - Can stretch body like rubber. Gear Second increases speed and strength. Gear Third enlarges body parts. Gear Fourth uses advanced Haki. Can use Conquerors Haki.',
    'Grew up in Foosha Village. Inspired by Red-Haired Shanks who saved his life and gave him the straw hat. Ate the Gum-Gum Devil Fruit as a child. Dreams of becoming the Pirate King.',
    'I''m gonna be King of the Pirates! I don''t want to conquer anything. I just think the guy with the most freedom in this ocean is the Pirate King!',
    'Captain of the Straw Hat Pirates. Best friend of Zoro. Brother of Ace and Sabo. Mentored by Shanks.',
    'Wears a red vest, blue shorts, sandals, and his signature straw hat. Has a scar under his left eye. Always smiling.',
    'protagonist'
),
(
    'Naruto Uzumaki',
    'Naruto',
    'Male',
    '17',
    'Blond',
    'Blue',
    'Ninja / Hokage',
    'Energetic, optimistic, never gives up, values friendship above all. Started as a troublemaker but became a hero. Extremely determined.',
    'Nine-Tails Chakra, Rasengan, Shadow Clone Jutsu, Sage Mode, Six Paths Sage Mode. Can create thousands of clones and use powerful chakra attacks.',
    'Orphaned as a baby when the Nine-Tails fox was sealed inside him. Grew up alone and hated by the village. Trained under Kakashi and Jiraiya. Dreams of becoming Hokage to gain recognition.',
    'Believe it! I never go back on my word, that''s my ninja way! I''m not gonna run away, I never go back on my word!',
    'Team 7 member with Sasuke and Sakura. Trained by Kakashi and Jiraiya. Best friend and rival of Sasuke. Married to Hinata.',
    'Orange jumpsuit, blond spiky hair, blue eyes, whisker marks on cheeks. Wears a headband with the Leaf Village symbol.',
    'protagonist'
),
(
    'Edward Elric',
    'Fullmetal Alchemist',
    'Male',
    '15-16',
    'Golden blond',
    'Gold',
    'State Alchemist',
    'Hot-headed, stubborn, intelligent, compassionate. Hates being called short. Dedicated to protecting his brother. Follows strong moral code.',
    'Alchemy without transmutation circles. Can transmute by clapping hands. Highly skilled in combat alchemy. Genius-level intellect in alchemical theory.',
    'Lost his right arm and left leg in a failed human transmutation attempt to revive his mother. Bonded his brother Alphonse''s soul to armor, losing his arm. Seeks the Philosopher''s Stone to restore their bodies.',
    'A lesson without pain is meaningless. Who are you calling so short you want to squash like an ant?!',
    'Younger brother of Alphonse. Student of Izumi Curtis. Works under Colonel Mustang. Partnered with Winry Rockbell.',
    'Short stature (very sensitive about it). Red coat with Flamel symbol. Metal automail right arm and left leg. Golden eyes and blond hair worn in a braid.',
    'protagonist'
),
(
    'Light Yagami',
    'Death Note',
    'Male',
    '17-23',
    'Brown',
    'Brown/Red (as Kira)',
    'Student / Mass Murderer',
    'Genius intellect, charismatic, manipulative, god complex. Started idealistic but became corrupted by power. Cold and calculating.',
    'Possesses the Death Note - can kill anyone by writing their name. Can see Shinigami. Exceptional strategic thinking and manipulation.',
    'Top student who found a Death Note dropped by Ryuk. Decided to create a new world free of crime by killing criminals. Became known as Kira. Engaged in cat-and-mouse game with detective L.',
    'I am Justice! I''ll take a potato chip... and eat it! The world is rotten, and those who are making it rot deserve to die.',
    'Son of police chief Soichiro Yagami. Rival of L. Partnered with Misa Amane. Followed by Shinigami Ryuk.',
    'Clean-cut appearance, brown hair, typically wears school uniform or business attire. Eyes take on sinister glow when acting as Kira.',
    'antagonist'
),
(
    'Goku',
    'Dragon Ball Z',
    'Male',
    '40+',
    'Black',
    'Black',
    'Martial Artist',
    'Pure-hearted, loves fighting strong opponents, protective of Earth, naive about social norms. Always training to get stronger.',
    'Super Saiyan transformations (1-3, God, Blue, Ultra Instinct). Kamehameha, Instant Transmission, Spirit Bomb. Extremely powerful martial artist.',
    'Born on Planet Vegeta as Kakarot. Sent to Earth as a baby. Hit his head and became kind. Trained under Master Roshi. Died and came back multiple times protecting Earth.',
    'I am the hope of the universe! It''s over 9000! I''ll never give up!',
    'Married to Chi-Chi. Father of Gohan and Goten. Trained by Master Roshi, King Kai, and Whis. Rival and friend of Vegeta.',
    'Spiky black hair, orange gi with blue shirt, muscular build. Hair turns gold when Super Saiyan.',
    'protagonist'
);

